### PR TITLE
Typo in README (probably also in source code; then do NOT commit)

### PR DESCRIPTION
**Pull request by PallHaraldsson**
If code needs to change, then might have a dilemma with making old user's code work..

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I have lots of questions. Any good place to ask them? Maybe "Julia forum" isn't it.. Here?

E.g. genie vs. https://github.com/shashi/Escher.jl

**Comment by EricForgy** [comment]
Hi @PallHaraldsson For questions, try: https://gitter.im/essenciary/Genie.jl

**Comment by EricForgy** [comment]
Hi @PallHaraldsson 

It might be good to change it here too: https://github.com/essenciary/Genie.jl/blob/61d8a1d946fc35e5914f379838ec1740d648b3bc/lib/Genie/src/Configuration.jl#L37

**Comment by EricForgy** [comment]
And here: https://github.com/essenciary/Genie.jl/search?utf8=%E2%9C%93&q=supress_output

:)

**Comment by EricForgy** [comment]
If you or @essenciary don't beat me to it, I can help make these changes later :+1: A bit busy at the moment :sweat_smile:

**Comment by essenciary** [comment]
Thanks! The typo is in the code as well - I'll just do a global replace and push, cheers!

**Pull request merged**
